# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false

contact_links:
  - name: "ğŸ“š é˜…è¯»README"
    url: https://github.com/krillinai/KlicStudio/blob/master/README.md
    about: "åœ¨æé—®å‰ï¼Œè¯·å…ˆæŸ¥çœ‹æ–‡æ¡£"

  - name: "â“ é—®é¢˜æé—®"
	  url: "https://github.com/krillinai/KlicStudio/blob/master/faq.md"
	  about: "éƒ¨åˆ†FAQ, æ›´å¤šé—®é¢˜å¯ä»¥åœ¨issueä¸­æŸ¥çœ‹"